// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPreviewController from "./audio_preview_controller"
application.register("audio-preview", AudioPreviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import SamplePackController from "./sample_pack_controller"
application.register("sample-pack", SamplePackController)
