require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sample_tags", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SampleTag. As you add validations to SampleTag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SampleTag.create! valid_attributes
      get sample_tags_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sample_tag = SampleTag.create! valid_attributes
      get sample_tag_url(sample_tag)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sample_tag_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sample_tag = SampleTag.create! valid_attributes
      get edit_sample_tag_url(sample_tag)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SampleTag" do
        expect {
          post sample_tags_url, params: { sample_tag: valid_attributes }
        }.to change(SampleTag, :count).by(1)
      end

      it "redirects to the created sample_tag" do
        post sample_tags_url, params: { sample_tag: valid_attributes }
        expect(response).to redirect_to(sample_tag_url(SampleTag.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SampleTag" do
        expect {
          post sample_tags_url, params: { sample_tag: invalid_attributes }
        }.to change(SampleTag, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sample_tags_url, params: { sample_tag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sample_tag" do
        sample_tag = SampleTag.create! valid_attributes
        patch sample_tag_url(sample_tag), params: { sample_tag: new_attributes }
        sample_tag.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sample_tag" do
        sample_tag = SampleTag.create! valid_attributes
        patch sample_tag_url(sample_tag), params: { sample_tag: new_attributes }
        sample_tag.reload
        expect(response).to redirect_to(sample_tag_url(sample_tag))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sample_tag = SampleTag.create! valid_attributes
        patch sample_tag_url(sample_tag), params: { sample_tag: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sample_tag" do
      sample_tag = SampleTag.create! valid_attributes
      expect {
        delete sample_tag_url(sample_tag)
      }.to change(SampleTag, :count).by(-1)
    end

    it "redirects to the sample_tags list" do
      sample_tag = SampleTag.create! valid_attributes
      delete sample_tag_url(sample_tag)
      expect(response).to redirect_to(sample_tags_url)
    end
  end
end
