require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sample_packs", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SamplePack. As you add validations to SamplePack, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SamplePack.create! valid_attributes
      get sample_packs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sample_pack = SamplePack.create! valid_attributes
      get sample_pack_url(sample_pack)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sample_pack_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      sample_pack = SamplePack.create! valid_attributes
      get edit_sample_pack_url(sample_pack)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SamplePack" do
        expect {
          post sample_packs_url, params: { sample_pack: valid_attributes }
        }.to change(SamplePack, :count).by(1)
      end

      it "redirects to the created sample_pack" do
        post sample_packs_url, params: { sample_pack: valid_attributes }
        expect(response).to redirect_to(sample_pack_url(SamplePack.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SamplePack" do
        expect {
          post sample_packs_url, params: { sample_pack: invalid_attributes }
        }.to change(SamplePack, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post sample_packs_url, params: { sample_pack: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sample_pack" do
        sample_pack = SamplePack.create! valid_attributes
        patch sample_pack_url(sample_pack), params: { sample_pack: new_attributes }
        sample_pack.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sample_pack" do
        sample_pack = SamplePack.create! valid_attributes
        patch sample_pack_url(sample_pack), params: { sample_pack: new_attributes }
        sample_pack.reload
        expect(response).to redirect_to(sample_pack_url(sample_pack))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        sample_pack = SamplePack.create! valid_attributes
        patch sample_pack_url(sample_pack), params: { sample_pack: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sample_pack" do
      sample_pack = SamplePack.create! valid_attributes
      expect {
        delete sample_pack_url(sample_pack)
      }.to change(SamplePack, :count).by(-1)
    end

    it "redirects to the sample_packs list" do
      sample_pack = SamplePack.create! valid_attributes
      delete sample_pack_url(sample_pack)
      expect(response).to redirect_to(sample_packs_url)
    end
  end
end
