test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean_spaces:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:digitalocean_spaces, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digitalocean_spaces, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:digitalocean_spaces, :region) %>
  endpoint: <%= Rails.application.credentials.dig(:digitalocean_spaces, :endpoint) %>
  bucket: <%= Rails.application.credentials.dig(:digitalocean_spaces, :bucket) %>
